<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="nextest-run" tests="2" failures="1" errors="0" uuid="17fb0f4a-f4d2-40b2-b229-ba30aac4b211" timestamp="2022-12-16T12:05:54.600+00:00" time="0.002">
    <testsuite name="tmp::bin/tmp" tests="2" disabled="0" errors="0" failures="1">
        <testcase name="foo::tests::should_pass" classname="tmp::bin/tmp" timestamp="2022-12-16T12:05:54.600+00:00" time="0.001">
        </testcase>
        <testcase name="foo::tests::should_fail" classname="tmp::bin/tmp" timestamp="2022-12-16T12:05:54.600+00:00" time="0.002">
            <failure type="test failure">thread &apos;foo::tests::should_fail&apos; panicked at src/foo.rs:10:9:
assertion failed: false
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace</failure>
            <system-out>
running 1 test
test foo::tests::should_fail ... FAILED

failures:

failures:
    foo::tests::should_fail

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 1 filtered out; finished in 0.00s

</system-out>
            <system-err>thread &apos;foo::tests::should_fail&apos; panicked at src/foo.rs:10:9:
assertion failed: false
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
</system-err>
        </testcase>
    </testsuite>
</testsuites>
